# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/clientUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import socket
import sys
import threading
import time

from PyQt5 import QtCore, QtGui, QtWidgets

from client import ChatClient
from common.utils import read_message_from_sock, write_message_to_sock
from common.vars import SENDER, MESSAGE_TEXT


class Ui_MainWindow(object):
    def __init__(self):
        self.sock = None
        self.chat_client_obj: ChatClient = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.contactsListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.contactsListWidget.setGeometry(QtCore.QRect(20, 100, 191, 191))
        self.contactsListWidget.setObjectName("contactsListWidget")
        self.chatTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.chatTextBrowser.setGeometry(QtCore.QRect(220, 100, 256, 191))
        self.chatTextBrowser.setObjectName("chatTextBrowser")
        self.contactLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.contactLineEdit.setGeometry(QtCore.QRect(20, 300, 191, 22))
        self.contactLineEdit.setObjectName("contactLineEdit")
        self.addContactPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.addContactPushButton.setGeometry(QtCore.QRect(20, 330, 91, 26))

        self.msgTextLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.msgTextLineEdit.setGeometry(QtCore.QRect(220, 300, 256, 22))
        self.msgTextLineEdit.setObjectName("msgTextLineEdit")

        self.addContactPushButton.setObjectName("addContactPushButton")
        self.sendMsgPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendMsgPushButton.setGeometry(QtCore.QRect(220, 330, 101, 26))
        self.sendMsgPushButton.setObjectName("sendMsgPushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 60, 16))
        self.label.setObjectName("label")
        self.chatLabel = QtWidgets.QLabel(self.centralwidget)
        self.chatLabel.setGeometry(QtCore.QRect(220, 80, 60, 16))
        self.chatLabel.setObjectName("chatLabel")
        self.serverIPLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.serverIPLineEdit.setGeometry(QtCore.QRect(20, 50, 113, 26))
        self.serverIPLineEdit.setObjectName("serverIPLineEdit")
        self.serverPortLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.serverPortLineEdit.setGeometry(QtCore.QRect(140, 50, 71, 26))
        self.serverPortLineEdit.setObjectName("serverPortLineEdit")
        self.connectPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectPushButton.setGeometry(QtCore.QRect(220, 50, 121, 26))
        self.connectPushButton.setObjectName("connectPushButton")
        self.loginLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.loginLineEdit.setGeometry(QtCore.QRect(20, 20, 113, 22))
        self.loginLineEdit.setObjectName("loginLineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.connectPushButton.clicked.connect(self.connect_to_server)
        self.sendMsgPushButton.clicked.connect(self.send_msg)
        self.addContactPushButton.clicked.connect(self.add_contact_to_list)

    def connect_to_server(self):
        if not self.chat_client_obj:
            addr = self.serverIPLineEdit.text()
            port = self.serverPortLineEdit.text()
            login = self.loginLineEdit.text()
            self.chat_client_obj = ChatClient(addr, port, login)
            self.sock = self.chat_client_obj.run_socket()

            write_message_to_sock(self.chat_client_obj.create_presence(), self.sock)
            presence_answer = self.chat_client_obj.process_ans(read_message_from_sock(self.sock))
            if presence_answer == '200 : OK':
                self.chatTextBrowser.append('Соединение с сервером успешно установлено.')
            else:
                self.chatTextBrowser.append(f'Сервер вернул ошибку: {presence_answer}')

            self.get_contacts()

            receiving_thread = threading.Thread(target=self.receive_msg)
            receiving_thread.daemon = True
            receiving_thread.start()

            sending_msg_thread = threading.Thread(target=self.send_msg)
            sending_msg_thread.daemon = True
            sending_msg_thread.start()

    def send_msg(self):
        self_user_login = self.chat_client_obj.client_name
        if (self.contactsListWidget.currentItem() is not None) & (self.msgTextLineEdit.text() != ''):
            message_receiver = self.contactsListWidget.currentItem().text()
            text = self.msgTextLineEdit.text()
            message = self.chat_client_obj.create_text_message(message_receiver, text)
            try:
                write_message_to_sock(message, self.sock)
                self.chat_client_obj.store_msg_to_db(message_receiver, text)
                self.chatTextBrowser.append(f'{self_user_login} to {message_receiver}: \n{text}')
            except socket.error as e:
                self.chatTextBrowser.append(f'потеряно соединение с сервером. {e}')

    def receive_msg(self):
        self_user_login = self.chat_client_obj.client_name
        while True:
            try:
                message = read_message_from_sock(self.sock)
                if message:
                    self.chatTextBrowser.append(f'{message[SENDER]} to {self_user_login}:\n {message[MESSAGE_TEXT]}')
            except socket.error as e:
                self.chatTextBrowser.append(f'потеряно соединение с сервером. {e}')

    def get_contacts(self):
        if self.chat_client_obj:
            self.contactsListWidget.addItems(self.chat_client_obj.get_contacts_from_db())
        else:
            self.chatTextBrowser.append('You should connect to server first')

    def add_contact_to_list(self):
        if self.contactLineEdit.text() is not '':
            new_contact_login = self.contactLineEdit.text()
            try:
                self.chat_client_obj.store_contact_to_db(new_contact_login, time.time())
            except Exception as err:
                self.chatTextBrowser.append(f'Fail to store new contact to DB:\n {err.args[0]}')
            self.contactsListWidget.clear()
            self.get_contacts()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addContactPushButton.setText(_translate("MainWindow", "Add Contact"))
        self.sendMsgPushButton.setText(_translate("MainWindow", "Send Message"))
        self.label.setText(_translate("MainWindow", "Contacts:"))
        self.chatLabel.setText(_translate("MainWindow", "Chat with "))
        self.serverIPLineEdit.setText(_translate("MainWindow", "127.0.0.1"))
        self.serverPortLineEdit.setText(_translate("MainWindow", "7777"))
        self.connectPushButton.setText(_translate("MainWindow", "Connect to server"))
        self.loginLineEdit.setText(_translate("MainWindow", "User_111"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
