# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serverUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import threading
from subprocess import Popen, PIPE

from PyQt5 import QtCore, QtGui, QtWidgets

import launcher
from server import ChatServer


class Ui_MainWindow(object):
    serverObj: ChatServer
    server_thread: threading.Thread

    def __init__(self):
        self.server_thread = None
        self.serverObj = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 533)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 191, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startServerBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startServerBtn.setObjectName("startServerBtn")
        self.verticalLayout.addWidget(self.startServerBtn)
        self.getClientsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.getClientsBtn.setObjectName("getClientsBtn")
        self.verticalLayout.addWidget(self.getClientsBtn)
        self.clientsListView = QtWidgets.QListView(self.centralwidget)
        self.clientsListView.setGeometry(QtCore.QRect(240, 70, 301, 192))
        self.clientsListView.setObjectName("clientsListView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.portEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.portEdit.setGeometry(QtCore.QRect(100, 20, 101, 22))
        self.portEdit.setObjectName("portEdit")
        self.consoleOutTextBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.consoleOutTextBrowser.setGeometry(QtCore.QRect(20, 290, 521, 191))
        self.consoleOutTextBrowser.setObjectName("consoleOutTextBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 270, 101, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.startServerBtn.clicked.connect(self.start_server_thread)
        self.getClientsBtn.clicked.connect(self.getClients)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat Server"))
        self.startServerBtn.setText(_translate("MainWindow", "Start Server"))
        self.getClientsBtn.setText(_translate("MainWindow", "Get Client"))
        self.label.setText(_translate("MainWindow", "Clients list"))
        self.label_2.setText(_translate("MainWindow", "Server Port:"))
        self.label_3.setText(_translate("MainWindow", "Console output:"))

    def start_server_thread(self):
        if not self.server_thread:
            try:
                port_num = int(self.portEdit.text())
                if not (0 < port_num) | (port_num > 65535):
                    raise ValueError('Port number should be > 0 and < 65535!!!')
            except ValueError as err:
                port_num = None
                self.consoleOutTextBrowser.setText(
                    'Port is incorrect. Starting server on default port\n' + err.args[0] + '\n')
            self.serverObj = ChatServer()
            self.server_thread = threading.Thread(target=lambda: self.serverObj.start_listen(port_num))
            self.consoleOutTextBrowser.append(f'Server started at port: {port_num if port_num else 7777}')
            self.server_thread.daemon = True
            self.server_thread.start()
        else:
            self.consoleOutTextBrowser.append('Server is already running!')

    def getClients(self):
        print(self.serverObj.contacts.keys())


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
