# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/clientUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ContactsListView = QtWidgets.QListView(self.centralwidget)
        self.ContactsListView.setEnabled(True)
        self.ContactsListView.setGeometry(QtCore.QRect(10, 30, 221, 501))
        self.ContactsListView.setObjectName("ContactsListView")
        self.HistoryTableView = QtWidgets.QTableView(self.centralwidget)
        self.HistoryTableView.setGeometry(QtCore.QRect(250, 30, 481, 371))
        self.HistoryTableView.setObjectName("HistoryTableView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 101, 16))
        self.label_2.setObjectName("label_2")
        self.enterMsgEditText = QtWidgets.QTextEdit(self.centralwidget)
        self.enterMsgEditText.setGeometry(QtCore.QRect(250, 430, 481, 101))
        self.enterMsgEditText.setObjectName("enterMsgEditText")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 410, 161, 16))
        self.label_3.setObjectName("label_3")
        self.addContactBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addContactBtn.setGeometry(QtCore.QRect(10, 540, 113, 32))
        self.addContactBtn.setObjectName("addContactBtn")
        self.sendMsgBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendMsgBtn.setGeometry(QtCore.QRect(250, 540, 113, 32))
        self.sendMsgBtn.setObjectName("sendMsgBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Contacts"))
        self.label_2.setText(_translate("MainWindow", "Chat Messages"))
        self.label_3.setText(_translate("MainWindow", "Enter message text here:"))
        self.addContactBtn.setText(_translate("MainWindow", "Add Contact"))
        self.sendMsgBtn.setText(_translate("MainWindow", "Send Message"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
